#!/usr/bin/env python3
"""Rewrite orange-core/Core/Natives.h to call natives by their canonical hash.

The 2017 code called every native by the hash the January 2017 game build
used, usually keeping the canonical hash (the one every natives database
uses, e.g. https://docs.fivem.net/natives) and the old 32-bit jhash in a
comment:

    static _Player PLAYER_ID() { return invoke<_Player>(0x0C1D3C552325765B); } // 0x4F8644AF03D0E0D6 0x8AEA886C

After this script the call uses the canonical hash and the comment records
the 2017 hash:

    static _Player PLAYER_ID() { return invoke<_Player>(0x4F8644AF03D0E0D6); } // 2017: 0x0C1D3C552325765B jhash 0x8AEA886C

The canonical hash comes from the comment, or from the function name for
unnamed natives (_0x...). Natives where neither exists are left as they are
and listed in tools/natives/natives-without-canonical.txt: their call hash
is the 2017 one, which the runtime uses unchanged when no translation exists.

orange-core/Core/NativeCrossmap_Reference.h receives the pairs
(canonical, 2017 hash) so that the reference build keeps working through the
same translation that natives-<version>.txt provides for other builds.

Usage: python3 tools/natives/canonicalize_natives.py   (idempotent)
"""
import re, sys, os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
NATIVES = os.path.join(ROOT, "orange-core", "Core", "Natives.h")
REFERENCE = os.path.join(ROOT, "orange-core", "Core", "NativeCrossmap_Reference.h")
REPORT = os.path.join(ROOT, "tools", "natives", "natives-without-canonical.txt")

INVOKE = re.compile(r"invoke<([^>]+)>\((0x[0-9A-Fa-f]{16})([,)])")
NAME = re.compile(r"static\s+[\w\s\*:<>]+?\s(_?[A-Za-z0-9_]+)\s*\(")
CONVERTED = re.compile(r"^\s*2017:\s*(0x[0-9A-Fa-f]{16})(?:\s+jhash\s+(0x[0-9A-Fa-f]{8}))?")
HASH64 = re.compile(r"\b(0x[0-9A-Fa-f]{16})\b")
HASH32 = re.compile(r"\b(0x[0-9A-Fa-f]{8})\b")
UNNAMED = re.compile(r"^_?0x([0-9A-Fa-f]{16})$")

pairs = {}          # canonical (lower) -> 2017 hash (lower)
conflicts = []
unresolved = []
changed = 0
out = []
with open(NATIVES, "r", encoding="latin-1") as f:
    for line in f:
        body = line.rstrip("\r\n")
        m = INVOKE.search(body)
        if not m:
            out.append(line)
            continue
        ret, callhash, sep = m.groups()
        comment_at = body.find("//", m.end())
        comment = body[comment_at + 2:] if comment_at >= 0 else ""
        code = body[:comment_at].rstrip() if comment_at >= 0 else body.rstrip()

        done = CONVERTED.search(comment)
        if done:
            pairs.setdefault(callhash.lower(), done.group(1).lower())
            out.append(line)
            continue

        canonical = None
        h64 = HASH64.search(comment)
        if h64:
            canonical = h64.group(1)
        else:
            n = NAME.search(body)
            if n:
                u = UNNAMED.match(n.group(1))
                if u:
                    canonical = "0x" + u.group(1)
        if not canonical:
            n = NAME.search(body)
            unresolved.append("%s %s" % (n.group(1) if n else "?", callhash))
            out.append(line)
            continue

        jh = HASH32.search(comment.replace(canonical, "")) if comment else None
        jhash = jh.group(1) if jh else None
        key = canonical.lower()
        if key in pairs and pairs[key] != callhash.lower():
            conflicts.append("%s -> %s and %s" % (canonical, pairs[key], callhash))
            out.append(line)
            continue
        pairs[key] = callhash.lower()

        new_code = code[:m.start()] + "invoke<%s>(%s%s" % (ret, canonical, sep) + code[m.end():]
        new_comment = " // 2017: %s" % callhash + (" jhash %s" % jhash if jhash else "")
        out.append(new_code + new_comment + "\n")
        changed += 1

with open(NATIVES, "w", encoding="latin-1", newline="") as f:
    f.writelines(out)

with open(REFERENCE, "w", encoding="ascii", newline="\n") as f:
    f.write("// Generated by tools/natives/canonicalize_natives.py from Natives.h. Do not edit.\n")
    f.write("// Canonical native hash -> hash used by the reference game build (January 2017).\n")
    f.write("#pragma once\n#include <cstddef>\n#include <cstdint>\n\n")
    f.write("static const uint64_t g_nativeCrossmapReference[][2] = {\n")
    for canonical in sorted(pairs):
        f.write("\t{ %sULL, %sULL },\n" % (canonical, pairs[canonical]))
    f.write("};\n")
    f.write("static const size_t g_nativeCrossmapReferenceCount = %d;\n" % len(pairs))

with open(REPORT, "w", encoding="ascii", newline="\n") as f:
    f.write("# Natives in orange-core/Core/Natives.h whose canonical hash is unknown.\n")
    f.write("# Format: <function name in Natives.h> <hash of the January 2017 build>\n")
    f.write("# Look the name up in a natives database (https://docs.fivem.net/natives), add\n")
    f.write("# '// 0x<canonical hash>' to the line in Natives.h and re-run this script.\n")
    for entry in unresolved:
        f.write(entry + "\n")
    if conflicts:
        f.write("# Conflicting entries (same canonical hash, different 2017 hash), left unchanged:\n")
        for c in conflicts:
            f.write("# " + c + "\n")

print("Natives.h: %d line(s) converted this run, %d native(s) in the reference crossmap, %d without canonical hash (see %s), %d conflict(s)"
      % (changed, len(pairs), len(unresolved), os.path.relpath(REPORT, ROOT), len(conflicts)))
