#include "stdafx.h"
#include "NativesCrossmap.h"
#include "Updater.h"
#include "LauncherLog.h"
#include "NativeCrossmapUniversal.h"

#include <fstream>
#include <sstream>

static const wchar_t* kUniversalUrl = L"https://raw.githubusercontent.com/citizenfx/fivem/master/code/components/rage-scripting-five/include/CrossMapping_Universal.h";

// "1.0.3889.0" -> 3889, 0 when the string does not look like a game version.
static int BuildNumberOf(const std::wstring& version)
{
	unsigned a = 0, b = 0, c = 0, d = 0;
	if (swscanf_s(version.c_str(), L"%u.%u.%u.%u", &a, &b, &c, &d) < 3)
		return 0;
	return (int)c;
}

static std::string Ascii(const std::wstring& text)
{
	std::string out;
	out.reserve(text.size());
	for (size_t i = 0; i < text.size(); ++i)
		out += text[i] < 128 ? (char)text[i] : '?';
	return out;
}

void EnsureNativesCrossmap(const std::wstring& installDir, const std::wstring& gameVersion)
{
	if (gameVersion.empty())
	{
		LauncherLog("natives: game version unknown, crossmap step skipped");
		return;
	}
	std::wstring path = installDir + L"\\natives-" + gameVersion + L".txt";
	if (GetFileAttributesW(path.c_str()) != INVALID_FILE_ATTRIBUTES)
	{
		LauncherLog(L"natives: " + path + L" present");
		return;
	}
	int build = BuildNumberOf(gameVersion);
	if (build < 350)
	{
		LauncherLog(L"natives: no crossmap needed for game version " + gameVersion);
		return;
	}

	LauncherLog(L"natives: " + path + L" missing, downloading FiveM's universal crossmap from " + kUniversalUrl);
	std::vector<char> data;
	std::string error;
	if (!Updater::DownloadUrl(kUniversalUrl, data, error))
	{
		LauncherLog("natives: download failed: " + error + " (orange-core will report the missing crossmap; tools/natives/crossmap_from_fivem.py generates it by hand)");
		return;
	}

	std::string text(data.begin(), data.end());
	std::string lines;
	orange::UniversalCrossmapStats stats;
	if (!orange::ConvertUniversalCrossmap(text, build, lines, stats, &error))
	{
		LauncherLog("natives: conversion failed: " + error);
		return;
	}

	std::ostringstream out;
	out << "; natives crossmap for GTA V " << Ascii(gameVersion) << ": <canonical hash> <hash of this build>\n"
		<< "; generated by the GTA:Orange launcher from FiveM's CrossMapping_Universal.h (column " << stats.column
		<< " of 28 for build " << build << "; the hashes are unchanged since 1.0.2944)\n"
		<< "; source: https://github.com/citizenfx/fivem, code/components/rage-scripting-five (Cfx.re / Take-Two terms); regenerated on demand, not redistributed\n"
		<< "; natives added after 1.0.2944 keep their canonical hash and need no line here; tools/natives/crossmap_from_fivem.py adds names\n"
		<< lines;

	std::ofstream file(path, std::ios::binary | std::ios::trunc);
	if (!file.good())
	{
		LauncherLog(L"natives: cannot write " + path);
		return;
	}
	std::string content = out.str();
	file.write(content.data(), (std::streamsize)content.size());
	file.close();
	std::ostringstream summary;
	summary << "natives: wrote " << stats.translations << " translation(s) for build " << build << " (" << stats.rows << " rows, "
		<< stats.identical << " unchanged, " << stats.absent << " not in this build) to " << Ascii(path);
	LauncherLog(summary.str());
}
